export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"主页","icon":"home","type":"home","readingTime":{"minutes":0,"words":0},"excerpt":""},["/index.html","/README.md"]],
  ["v-00ba2c54","/blog/hello-world.html",{"title":"这是我的第一篇vuepress文章","type":"article","readingTime":{"minutes":0.01,"words":2},"excerpt":"","category":["vuepress"],"tag":["vuepress"]},["/blog/hello-world","/blog/hello-world.md"]],
  ["v-06fcdc21","/web/css/%E5%9F%BA%E7%A1%80.html",{"title":"基础","type":"page","readingTime":{"minutes":5.4,"words":1619},"excerpt":""},["/web/css/基础.html","/web/css/%E5%9F%BA%E7%A1%80","/web/css/基础.md","/web/css/%E5%9F%BA%E7%A1%80.md"]],
  ["v-da729486","/web/css/%E5%AD%97%E4%BD%93.html",{"title":"字体","type":"page","readingTime":{"minutes":1.87,"words":561},"excerpt":""},["/web/css/字体.html","/web/css/%E5%AD%97%E4%BD%93","/web/css/字体.md","/web/css/%E5%AD%97%E4%BD%93.md"]],
  ["v-7bf23498","/web/css/%E5%AE%9A%E4%BD%8D.html",{"title":"定位","type":"page","readingTime":{"minutes":2.79,"words":836},"excerpt":""},["/web/css/定位.html","/web/css/%E5%AE%9A%E4%BD%8D","/web/css/定位.md","/web/css/%E5%AE%9A%E4%BD%8D.md"]],
  ["v-a598cb56","/web/css/%E5%B8%83%E5%B1%80.html",{"title":"布局(网页默认)","type":"page","readingTime":{"minutes":5.28,"words":1584},"excerpt":""},["/web/css/布局.html","/web/css/%E5%B8%83%E5%B1%80","/web/css/布局.md","/web/css/%E5%B8%83%E5%B1%80.md"]],
  ["v-4ecc8dfd","/web/css/%E6%B5%AE%E5%8A%A8.html",{"title":"浮动","type":"page","readingTime":{"minutes":3.45,"words":1036},"excerpt":""},["/web/css/浮动.html","/web/css/%E6%B5%AE%E5%8A%A8","/web/css/浮动.md","/web/css/%E6%B5%AE%E5%8A%A8.md"]],
  ["v-b3d28df4","/web/css/%E8%83%8C%E6%99%AF.html",{"title":"背景","type":"page","readingTime":{"minutes":1.46,"words":438},"excerpt":""},["/web/css/背景.html","/web/css/%E8%83%8C%E6%99%AF","/web/css/背景.md","/web/css/%E8%83%8C%E6%99%AF.md"]],
  ["v-d11af81e","/web/html/%E5%9F%BA%E7%A1%80.html",{"title":"基础","type":"page","readingTime":{"minutes":5.33,"words":1598},"excerpt":""},["/web/html/基础.html","/web/html/%E5%9F%BA%E7%A1%80","/web/html/基础.md","/web/html/%E5%9F%BA%E7%A1%80.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-43d7543a","/category/vuepress/",{"title":"vuepress 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/vuepress/index.html"]],
  ["v-ed16b278","/tag/vuepress/",{"title":"vuepress 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/vuepress/index.html"]],
]
