export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"主页","icon":"home","type":"home","readingTime":{"minutes":0,"words":0},"excerpt":""},["/index.html","/README.md"]],
  ["v-74bc627b","/about/",{"title":"关于我","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/about/index.html","/about/readme.md"]],
  ["v-1a932c19","/blog/%E4%BD%BF%E7%94%A8Algolia.html",{"title":"使用Algolia用作网站搜索","type":"article","readingTime":{"minutes":1.42,"words":426},"excerpt":"","category":["vuepress"],"tag":["vuepress"]},["/blog/使用Algolia.html","/blog/%E4%BD%BF%E7%94%A8Algolia","/blog/使用Algolia.md","/blog/%E4%BD%BF%E7%94%A8Algolia.md"]],
  ["v-c6755c5a","/blog/%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.html",{"title":"个人学习记录","type":"article","readingTime":{"minutes":0.6,"words":180},"excerpt":"","category":["学习"],"tag":["学习"]},["/blog/学习记录.html","/blog/%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95","/blog/学习记录.md","/blog/%E5%AD%A6%E4%B9%A0%E8%AE%B0%E5%BD%95.md"]],
  ["v-118443c0","/web/css/flex.html",{"title":"flex","type":"page","readingTime":{"minutes":2.06,"words":619},"excerpt":""},["/web/css/flex","/web/css/flex.md"]],
  ["v-bb307540","/web/css/%E5%8A%A8%E7%94%BB.html",{"title":"动画","type":"page","readingTime":{"minutes":1.68,"words":505},"excerpt":""},["/web/css/动画.html","/web/css/%E5%8A%A8%E7%94%BB","/web/css/动画.md","/web/css/%E5%8A%A8%E7%94%BB.md"]],
  ["v-11d1823e","/web/css/%E5%93%8D%E5%BA%94%E5%BC%8F.html",{"title":"响应式","type":"page","readingTime":{"minutes":0.83,"words":248},"excerpt":""},["/web/css/响应式.html","/web/css/%E5%93%8D%E5%BA%94%E5%BC%8F","/web/css/响应式.md","/web/css/%E5%93%8D%E5%BA%94%E5%BC%8F.md"]],
  ["v-06fcdc21","/web/css/%E5%9F%BA%E7%A1%80.html",{"title":"基础","type":"page","readingTime":{"minutes":5.38,"words":1614},"excerpt":""},["/web/css/基础.html","/web/css/%E5%9F%BA%E7%A1%80","/web/css/基础.md","/web/css/%E5%9F%BA%E7%A1%80.md"]],
  ["v-da729486","/web/css/%E5%AD%97%E4%BD%93.html",{"title":"字体","type":"page","readingTime":{"minutes":1.86,"words":559},"excerpt":""},["/web/css/字体.html","/web/css/%E5%AD%97%E4%BD%93","/web/css/字体.md","/web/css/%E5%AD%97%E4%BD%93.md"]],
  ["v-7bf23498","/web/css/%E5%AE%9A%E4%BD%8D.html",{"title":"定位","type":"page","readingTime":{"minutes":2.79,"words":836},"excerpt":""},["/web/css/定位.html","/web/css/%E5%AE%9A%E4%BD%8D","/web/css/定位.md","/web/css/%E5%AE%9A%E4%BD%8D.md"]],
  ["v-a598cb56","/web/css/%E5%B8%83%E5%B1%80.html",{"title":"布局(网页默认)","type":"page","readingTime":{"minutes":5.28,"words":1584},"excerpt":""},["/web/css/布局.html","/web/css/%E5%B8%83%E5%B1%80","/web/css/布局.md","/web/css/%E5%B8%83%E5%B1%80.md"]],
  ["v-ba6fb42c","/web/css/%E6%89%8B%E6%9C%BA%E7%AB%AF.html",{"title":"手机端","type":"page","readingTime":{"minutes":1.98,"words":594},"excerpt":""},["/web/css/手机端.html","/web/css/%E6%89%8B%E6%9C%BA%E7%AB%AF","/web/css/手机端.md","/web/css/%E6%89%8B%E6%9C%BA%E7%AB%AF.md"]],
  ["v-4ecc8dfd","/web/css/%E6%B5%AE%E5%8A%A8.html",{"title":"浮动","type":"page","readingTime":{"minutes":3.45,"words":1036},"excerpt":""},["/web/css/浮动.html","/web/css/%E6%B5%AE%E5%8A%A8","/web/css/浮动.md","/web/css/%E6%B5%AE%E5%8A%A8.md"]],
  ["v-b3d28df4","/web/css/%E8%83%8C%E6%99%AF.html",{"title":"背景","type":"page","readingTime":{"minutes":1.45,"words":436},"excerpt":""},["/web/css/背景.html","/web/css/%E8%83%8C%E6%99%AF","/web/css/背景.md","/web/css/%E8%83%8C%E6%99%AF.md"]],
  ["v-d11af81e","/web/html/%E5%9F%BA%E7%A1%80.html",{"title":"基础","type":"page","readingTime":{"minutes":5.33,"words":1598},"excerpt":""},["/web/html/基础.html","/web/html/%E5%9F%BA%E7%A1%80","/web/html/基础.md","/web/html/%E5%9F%BA%E7%A1%80.md"]],
  ["v-3706649a","/404.html",{"title":"","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/404"]],
  ["v-5bc93818","/category/",{"title":"分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/index.html"]],
  ["v-744d024e","/tag/",{"title":"标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/index.html"]],
  ["v-e52c881c","/article/",{"title":"文章","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/article/index.html"]],
  ["v-75ed4ea4","/encrypted/",{"title":"加密","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/encrypted/index.html"]],
  ["v-d804e652","/slide/",{"title":"幻灯片","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/slide/index.html"]],
  ["v-154dc4c4","/star/",{"title":"收藏","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/star/index.html"]],
  ["v-01560935","/timeline/",{"title":"时间轴","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/timeline/index.html"]],
  ["v-43d7543a","/category/vuepress/",{"title":"vuepress 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/vuepress/index.html"]],
  ["v-ed16b278","/tag/vuepress/",{"title":"vuepress 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/vuepress/index.html"]],
  ["v-52a9f9b2","/category/%E5%AD%A6%E4%B9%A0/",{"title":"学习 分类","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/category/学习/","/category/%E5%AD%A6%E4%B9%A0/index.html"]],
  ["v-7c9127bc","/tag/%E5%AD%A6%E4%B9%A0/",{"title":"学习 标签","type":"page","readingTime":{"minutes":0,"words":0},"excerpt":""},["/tag/学习/","/tag/%E5%AD%A6%E4%B9%A0/index.html"]],
]
